sudo: true
dist: trusty
language: node_js

node_js:
   - node # will use latest node

addons:
  chrome: stable

script: # the build step
   - npm run test-coverage
   - npm run build

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

cache:
  yarn: true
  directories:
    - ./node_modules/

branches:
  only:
  - master
